### PR TITLE
latest ee-docs-importer package

### PR DESCRIPTION
**Pull request by thomasm0**

### CODE REVIEW

**Review by SireeKoolenWijkstra — APPROVED** [review]
lgtm

**Comment by thomasm0** [comment]
I've updated this so it now also references the package via tags, @SireeKoolenWijkstra can you try again?

**Review by SireeKoolenWijkstra — CHANGES_REQUESTED** [review]
What is it supposed to do? Fix the problem with the commithash of the ee-docs-importer? (See [Slack](https://datalab-amsterdam.slack.com/archives/D06E1QK0BT4/p1723144986700879)) Because it aint doing that. There is an update to our standards in storing source code (the update date of the standard has changed) that doesn't change with it.

**Review by SireeKoolenWijkstra — APPROVED** [review]
as discussed

**Pull request merged**
